/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RateRouteImport } from './routes/rate'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HoroscopeRouteImport } from './routes/horoscope'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AstroRouteImport } from './routes/astro'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizResultRouteImport } from './routes/quiz.result'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const RateRoute = RateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeRoute = HoroscopeRouteImport.update({
  id: '/horoscope',
  path: '/horoscope',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroRoute = AstroRouteImport.update({
  id: '/astro',
  path: '/astro',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizRoute,
} as any)
const QuizResultRoute = QuizResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => QuizRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/astro': typeof AstroRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/generator': typeof GeneratorRoute
  '/horoscope': typeof HoroscopeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRouteWithChildren
  '/rate': typeof RateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quiz/result': typeof QuizResultRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/astro': typeof AstroRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/generator': typeof GeneratorRoute
  '/horoscope': typeof HoroscopeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/rate': typeof RateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quiz/result': typeof QuizResultRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/astro': typeof AstroRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/generator': typeof GeneratorRoute
  '/horoscope': typeof HoroscopeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRouteWithChildren
  '/rate': typeof RateRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quiz/result': typeof QuizResultRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/astro'
    | '/complete-profile'
    | '/generator'
    | '/horoscope'
    | '/login'
    | '/profile'
    | '/quiz'
    | '/rate'
    | '/auth/callback'
    | '/quiz/result'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/astro'
    | '/complete-profile'
    | '/generator'
    | '/horoscope'
    | '/login'
    | '/profile'
    | '/rate'
    | '/auth/callback'
    | '/quiz/result'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/astro'
    | '/complete-profile'
    | '/generator'
    | '/horoscope'
    | '/login'
    | '/profile'
    | '/quiz'
    | '/rate'
    | '/auth/callback'
    | '/quiz/result'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  AstroRoute: typeof AstroRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  GeneratorRoute: typeof GeneratorRoute
  HoroscopeRoute: typeof HoroscopeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRouteWithChildren
  RateRoute: typeof RateRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope': {
      id: '/horoscope'
      path: '/horoscope'
      fullPath: '/horoscope'
      preLoaderRoute: typeof HoroscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astro': {
      id: '/astro'
      path: '/astro'
      fullPath: '/astro'
      preLoaderRoute: typeof AstroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/result': {
      id: '/quiz/result'
      path: '/result'
      fullPath: '/quiz/result'
      preLoaderRoute: typeof QuizResultRouteImport
      parentRoute: typeof QuizRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuizRouteChildren {
  QuizResultRoute: typeof QuizResultRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizResultRoute: QuizResultRoute,
  QuizIndexRoute: QuizIndexRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  AstroRoute: AstroRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  GeneratorRoute: GeneratorRoute,
  HoroscopeRoute: HoroscopeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRouteWithChildren,
  RateRoute: RateRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
